name: decrypt_utils
description: Utility scripts for decryption
version: 0.1.0
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  encrypt: ^5.0.1
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0


